# Generated by Django 4.1.3 on 2023-01-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
